const properties = [
  {
    id: "1",
    address: "Bergstraße 14, Garmisch-Partenkirchen, Germany",
    isAvailable: true,
    energyClass: "B",
    buy: 520000,
    rent: null,
    photo: "/photos/residence_1.jpg",
    rooms: 7,
    squareMeters: 160,
    category: "Residence",
    yearBuilt: 1998,
  },
  {
    id: "2",
    address: "Tulpenweg 77, Lüneburg, Germany",
    isAvailable: true,
    energyClass: "C",
    buy: null,
    rent: 950,
    photo: "/photos/apartment_1.jpg",
    rooms: 3,
    squareMeters: 68,
    category: "Apartment",
    yearBuilt: 2005,
  },
  {
    id: "3",
    address: "Åsveien 9, Lillehammer, Norway",
    isAvailable: false,
    energyClass: "A",
    buy: 410000,
    rent: null,
    photo: "/photos/chalet_1.jpg",
    rooms: 5,
    squareMeters: 110,
    category: "Chalet",
    yearBuilt: 1987,
  },
  {
    id: "4",
    address: "Via del Bosco 21, Merano, Italy",
    isAvailable: true,
    energyClass: "B",
    buy: null,
    rent: 2100,
    photo: "/photos/residence_2.jpg",
    rooms: 7,
    squareMeters: 175,
    category: "Townhouse",
    yearBuilt: 2012,
  },
  {
    id: "5",
    address: "Rue des Tilleuls 3, Colmar, France",
    isAvailable: true,
    energyClass: "D",
    buy: null,
    rent: 780,
    photo: "/photos/apartment_2.jpg",
    rooms: 2,
    squareMeters: 38,
    category: "Studio",
    yearBuilt: 1992,
  },
  {
    id: "6",
    address: "Kerkstraat 6, Delft, Netherlands",
    isAvailable: true,
    energyClass: "C",
    buy: 320000,
    rent: null,
    photo: "/photos/chalet_2.jpg",
    rooms: 3,
    squareMeters: 85,
    category: "Chalet",
    yearBuilt: 1978,
  },
  {
    id: "7",
    address: "Skovvej 48, Odense, Denmark",
    isAvailable: false,
    energyClass: "A+",
    buy: 690000,
    rent: null,
    photo: "/photos/residence_3.jpg",
    rooms: 8,
    squareMeters: 210,
    category: "Residence",
    yearBuilt: 2018,
  },
  {
    id: "8",
    address: "Calle del Prado 12, Segovia, Spain",
    isAvailable: true,
    energyClass: "B",
    buy: null,
    rent: 1050,
    photo: "/photos/apartment_3.jpg",
    rooms: 4,
    squareMeters: 75,
    category: "Apartment",
    yearBuilt: 2009,
  },
  {
    id: "9",
    address: "Rue du Moulin 2, Annecy, France",
    isAvailable: true,
    energyClass: "C",
    buy: 450000,
    rent: null,
    photo: "/photos/chalet_3.jpg",
    rooms: 5,
    squareMeters: 98,
    category: "Chalet",
    yearBuilt: 1984,
  },
  {
    id: "10",
    address: "Via Roma 19, Trento, Italy",
    isAvailable: true,
    energyClass: "A",
    buy: 890000,
    rent: null,
    photo: "/photos/residence_4.jpg",
    rooms: 10,
    squareMeters: 260,
    category: "Residence",
    yearBuilt: 2015,
  },
  {
    id: "11",
    address: "Hauptstraße 5, Quedlinburg, Germany",
    isAvailable: true,
    energyClass: "D",
    buy: null,
    rent: 820,
    photo: "/photos/apartment_4.jpg",
    rooms: 2,
    squareMeters: 52,
    category: "Apartment",
    yearBuilt: 1990,
  },
  {
    id: "12",
    address: "Rue de la Gare 11, Arlon, Belgium",
    isAvailable: false,
    energyClass: "C",
    buy: 275000,
    rent: null,
    photo: "/photos/chalet_4.jpg",
    rooms: 3,
    squareMeters: 82,
    category: "Chalet",
    yearBuilt: 1981,
  },
  {
    id: "13",
    address: "Storgatan 33, Uppsala, Sweden",
    isAvailable: true,
    energyClass: "B",
    buy: null,
    rent: 1750,
    photo: "/photos/residence_5.jpg",
    rooms: 5,
    squareMeters: 140,
    category: "Townhouse",
    yearBuilt: 2003,
  },
  {
    id: "14",
    address: "Rua das Flores 10, Braga, Portugal",
    isAvailable: true,
    energyClass: "C",
    buy: 310000,
    rent: null,
    photo: "/photos/apartment_5.jpg",
    rooms: 3,
    squareMeters: 72,
    category: "Apartment",
    yearBuilt: 1996,
  },
  {
    id: "15",
    address: "Via delle Rose 7, Bolzano, Italy",
    isAvailable: true,
    energyClass: "B",
    buy: 480000,
    rent: null,
    photo: "/photos/chalet_5.jpg",
    rooms: 6,
    squareMeters: 125,
    category: "Chalet",
    yearBuilt: 1989,
  },
  {
    id: "16",
    address: "Rue du Lac 2, Lausanne, Switzerland",
    isAvailable: true,
    energyClass: "D",
    buy: null,
    rent: 760,
    photo: "/photos/apartment_6.jpg",
    rooms: 2,
    squareMeters: 42,
    category: "Studio",
    yearBuilt: 1994,
  },
  {
    id: "17",
    address: "Hauptplatz 8, Villach, Austria",
    isAvailable: true,
    energyClass: "A",
    buy: 520000,
    rent: null,
    photo: "/photos/residence_6.jpg",
    rooms: 5,
    squareMeters: 145,
    category: "Residence",
    yearBuilt: 2010,
  },
  {
    id: "18",
    address: "Calle Mayor 15, Pamplona, Spain",
    isAvailable: false,
    energyClass: "B",
    buy: null,
    rent: 1300,
    photo: "/photos/chalet_6.jpg",
    rooms: 5,
    squareMeters: 95,
    category: "Apartment",
    yearBuilt: 2007,
  },
];

export default properties;
