name: Keep Render Alive

# prevent Render backend from going to sleep (= cold starts) by pinging API endpoint regularly

on:
  schedule:
    - cron: "*/12 * * * *" # run every 12 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: curl -Is https://homesphere-kifc.onrender.com/api/entries || true
